updated del: made more resilient

diff --git a/studio1/del b/studio1/del
--- a/studio1/del
+++ b/studio1/del
@@ -4,9 +4,14 @@
 mkdir -p ~/.waste
 
 # Test if we are attempting to delete a directory and error.
-if [ -d "$1" ]
-then echo "del: cannot delete $1: Is a directory."
-	exit 1
-else mv "$1" ~/.waste
+if [[ -e "$1" ]]; then
+    if [[ -d "$1" ]]; then
+        echo "del: cannot delete $1: Is a directory."
+	    exit 1
+    else
+        mv "$1" ~/.waste
+    fi
+else
+    echo "del: please give a file to delete."
 fi
 
