updated del: updated comments

diff --git a/studio1/del b/studio1/del
--- a/studio1/del
+++ b/studio1/del
@@ -3,15 +3,17 @@
 # Make the waste directory in the users home directory if it does not exist.
 mkdir -p ~/.waste
 
-# Test if we are attempting to delete a directory and error.
+# Test if we are attempting to delete a file.
 if [[ -e "$1" ]]; then
+    # Test if we are attempting to delete a directory.
     if [[ -d "$1" ]]; then
-        echo "del: cannot delete $1: Is a directory."
+        echo "Cannot delete $1: Is a directory."
 	    exit 1
     else
         mv "$1" ~/.waste
     fi
 else
-    echo "del: please give a file to delete."
+    echo "Please give a file to delete."
+    exit 1
 fi
 
